### ISSUE TITLE
(1146, "Table 'juju.db_user' doesn't exist")

### ISSUE THREAD

**Issue by 8secz-johndpope** [AiryMiku/zhbit_juju_backend#41]
Does this require some missing schema db_user?

**Comment by 8secz-johndpope** [comment]
Django version 2.2.1, using settings 'zhbit_juju_backend.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
method：POST
Internal Server Error: /user/login/
Traceback (most recent call last):
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1146, "Table 'juju.db_user' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/johndpope/Documents/gitWorkspace/zhbit_juju_backend/apps/http/user/controller/LoginController.py", line 23, in login
    obj = models.User.objects.get(account_name=_param['account_name'])
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'juju.db_user' doesn't exist")
[26/Jun/2019 10:06:16] "POST /user/login/ HTTP/1.1" 500 159919

**Comment by 8secz-johndpope** [comment]
fixed - https://github.com/AiryMiku/zhbit_juju_backend/pull/40/files#diff-26205fa396afae7e698346556c23f256

**Comment by AiryMiku** [comment]
I forgot merge feature branch to master, now you can update and try again🙃I will take that pull request, thanks.
