### ISSUE TITLE
sign up user / apps.http.db.models.User.DoesNotExist: User matching query does not exist.

### ISSUE THREAD

**Issue by 8secz-johndpope** [AiryMiku/zhbit_juju_backend#42]
Internal Server Error: /user/register/
Traceback (most recent call last):
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/johndpope/Documents/gitWorkspace/zhbit_juju_backend/apps/http/user/controller/RegisterController.py", line 15, in register
    exist = models.User.objects.get(account_name = _param['account_name'])
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/johndpope/miniconda3/envs/juju/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
apps.http.db.models.User.DoesNotExist: User matching query does not exist.
[26/Jun/2019 10:24:54] "POST /user/register/ HTTP/1.1" 500 75573

![Screen Shot 2019-06-26 at 12 25 36 pm](https://user-images.githubusercontent.com/50567111/60146608-8b440b80-980d-11e9-912b-2b349b6b8581.png)

<img width="354" alt="Screen Shot 2019-06-26 at 12 26 17 pm" src="https://user-images.githubusercontent.com/50567111/60146625-9e56db80-980d-11e9-8e46-3309dbc152db.png">

**Comment by 8secz-johndpope** [comment]
it would be good if there was a mock database with users we could load.
restore from sql backup.

**Comment by AiryMiku** [comment]
fixed
